name: 'Check Workflow Status'
description: 'Check the status of workflow'

inputs:
  needs:
    description: 'The needs context containing the job information'
    required: true
outputs:
  workflow_succeeded:
    description: 'Whether workflow have succeeded'
    value: ${{ steps.check_status.outputs.workflow_succeeded }}

runs:
  using: 'composite'
  steps:
    - name: Check Job Status
      id: check_status
      run: |
        needs_json=$(echo "${{ toJSON(inputs.needs) }}" | sed 's/n//g')
        echo "$needs_json" | jq -c '.[] | .result' | while read -r result; do
          if [ "$result" != '"success"' ]; then
            echo "job failure" > failure.txt
            break
          fi
        done
        if [ -e failure.txt ]; then
          echo "workflow_succeeded=false" >> $GITHUB_OUTPUT
        else
          echo "workflow_succeeded=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
