name: 'Check Job Status'
description: 'Check the status of all jobs'

inputs:
  jobs:
    description: 'The needs context containing the job information'
    required: true
outputs:
  all_jobs_succeeded:
    description: 'Whether all jobs have succeeded'
    value: ${{ steps.check_status.outputs.all_jobs_succeeded }}

runs:
  using: 'composite'
  steps:
    - name: Check Job Status
      id: check_status
      run: |
        all_jobs_succeeded=true
        jobs_json='${{ toJSON(inputs.jobs) }}'
        for job_key in $(echo "$jobs_json" | jq -r 'keys[]'); do
          echo "デバッグ開始"
          echo $job_key
          echo "デバッグ終了"
        done
        echo "all_jobs_succeeded=$all_jobs_succeeded" >> $GITHUB_OUTPUT
      shell: bash
