name: sample-job

on:
  push:

jobs:
  job-1:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: job-1 output-1
        run: echo Job1 Hello1
      - name: job-1 output-2
        run: echo Job1 Hello2

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    timeout-minutes: 10
    steps:
      - name: job-2 output-1
        run: echo Job2 Hello1
      - name: job-2 output-2
        run: echo Job2 Hello2

  notify:
    runs-on: ubuntu-latest
    needs: [job-1, job-2]
    if: ${{ always() }}
    steps:
      - name: notify
        run: echo '${{ toJSON(needs) }}'
