name: sample-job

on:
  push:

jobs:
  job-a:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: job-a output-1
        run: echo Job1 Hello1
      - name: job-a output-2
        run: echo Job1 Hello2

  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    timeout-minutes: 10
    steps:
      - name: exit
        run: exit 1
      - name: job-b output-1
        run: echo Job2 Hello1

  job-c:
    runs-on: ubuntu-latest
    needs: [job-a, job-b]
    timeout-minutes: 10
    steps:
      - name: job-c output-1
        run: echo Job3 Hello1
      - name: job-c output-2
        run: echo Job3 Hello2

  notify:
    runs-on: ubuntu-latest
    needs: [job-a, job-b, job-c]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - name: Check Job Status
        id: check_status
        uses: ./.github/actions/check-job-status
        with:
          needs: ${{ toJSON(needs) }}
      - name: notify-success
        if: steps.check_status.outputs.all_jobs_succeeded == 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: good
          # SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'デプロイ成功 :rocket:'
          SLACK_TITLE: デプロイ成功
          SLACK_USERNAME: デプロイ結果通知
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: notify-failure
        if: steps.check_status.outputs.all_jobs_succeeded == 'false'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          # SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'デプロイ成功 :rocket:'
          SLACK_TITLE: デプロイ失敗
          SLACK_USERNAME: デプロイ結果通知
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
