name: sample-job

on:
  push:

jobs:
  job-1:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: job-1 output-1
        run: echo Job1 Hello1
      - name: job-1 output-2
        run: echo Job1 Hello2

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    timeout-minutes: 10
    steps:
      # - name: exit
      #   run: exit 1
      - name: job-2 output-1
        run: echo Job2 Hello1

  job-3:
    runs-on: ubuntu-latest
    needs: [job-1, job-2]
    timeout-minutes: 10
    steps:
      - name: job-3 output-1
        run: echo Job3 Hello1
      - name: job-3 output-2
        run: echo Job3 Hello2

  notify:
    runs-on: ubuntu-latest
    needs: [job-1, job-2, job-3]
    timeout-minutes: 10
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - name: Check Job Status
        id: check_status
        uses: ./.github/actions/check-job-status
        with:
          jobs: ${{ toJSON(needs) }}
      - name: notify-success
        if: steps.check_status.outputs.all_jobs_succeeded == 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          # SLACK_CHANNEL: general
          SLACK_COLOR: good
          # SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'デプロイ成功 :rocket:'
          SLACK_TITLE: デプロイ成功
          SLACK_USERNAME: デプロイ結果通知
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: notify-failure
        if: steps.check_status.outputs.all_jobs_succeeded == 'false'
        uses: rtCamp/action-slack-notify@v2
        env:
          # SLACK_CHANNEL: general
          SLACK_COLOR: danger
          # SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'デプロイ失敗 :warning:'
          SLACK_TITLE: デプロイ失敗
          SLACK_USERNAME: デプロイ結果通知
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
